### ISSUE TITLE
asyncpg.exceptions._base.InterfaceError: cannot perform operation: another operation is in progress

### ISSUE THREAD

**Issue by hhertogh** [grillazz/fastapi-sqlalchemy-asyncpg#63]
Hey,
I'm using your boilerplate to setup my fastapi with sqlalchemy and asyncpg.
Now when I do some load testing on my API, after a few concurrent requests , I have the following issue:
asyncpg.exceptions._base.InterfaceError: cannot perform operation: another operation is in progress
How can I prevent this ?
Thanks,
Henry

**Comment by grillazz** [comment]
@hhertogh could you please paste your full trace here and maybe code snipes which allow to reproduce me this issue ?

**Comment by hhertogh** [comment]
Hey @grillazz , thanks for your answer.

This is my dbsetup.py , from which get_session is injected as a dependency:

```
engine = create_async_engine(
    'postgresql+asyncpg://...',
    future=True,
    echo=True,
    echo_pool=True,
    pool_size=20,
    pool_timeout=60,
    json_serializer=jsonable_encoder
)

# expire_on_commit=False will prevent attributes from being expired
# after commit.
async_session_factory = sessionmaker(engine, expire_on_commit=False, class_=AsyncSession)
AsyncScopedSession = async_scoped_session(async_session_factory, scopefunc=current_task)

#method that can be used as a dependency in fastapi routes
async def get_session() -> AsyncGenerator:
    async with async_session_factory() as session:
        try:
            yield session
        except SQLAlchemyError as sql_ex:
            if session:
                await session.rollback()
            raise sql_ex
        except HTTPException as http_ex:
            if session:
                await session.rollback()
            raise http_ex
        finally:
            await session.close()
```

As you can see I have added the pool_size parameter to see if this had impact but not really ...

I'm using the session in a separate class that has specific queries on the DB.

On a few sub-functions I have to pass the session through the request.state as otherwise it's not available.

The error is happening when I do a 10 concurrent requests for a few seconds with some waiting time between the requests...  it's often happening in the same function in the db class that has a few db queries to execute ...

The error trace:

```
  File "/venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 442, in _prepare_and_execute
    self._rows = await prepared_stmt.fetch(*parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/asyncpg/prepared_stmt.py", line 176, in fetch
    data = await self.__bind_execute(args, 0, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/asyncpg/prepared_stmt.py", line 241, in __bind_execute
    data, status, _ = await self.__do_execute(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/asyncpg/prepared_stmt.py", line 230, in __do_execute
    return await executor(protocol)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 181, in bind_execute
  File "asyncpg/protocol/protocol.pyx", line 707, in asyncpg.protocol.protocol.BaseProtocol._check_state
asyncpg.exceptions._base.InterfaceError: cannot perform operation: another operation is in progress

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 479, in execute
    self._adapt_connection.await_(
  File "/venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 68, in await_only
    return current.driver.switch(awaitable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 121, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 454, in _prepare_and_execute
    self._handle_exception(error)
  File "/venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 389, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 682, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.InterfaceError: <class 'asyncpg.exceptions._base.InterfaceError'>: cannot perform operation: another operation is in progress

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/backbone-api/app/db.py", line 273, in start_execution
    await self.mysession.execute(stmt)
  File "/venv/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py", line 214, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 126, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/venv/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 479, in execute
    self._adapt_connection.await_(
  File "/venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 68, in await_only
    return current.driver.switch(awaitable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 121, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 454, in _prepare_and_execute
    self._handle_exception(error)
  File "/venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 389, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 682, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.InterfaceError: (sqlalchemy.dialects.postgresql.asyncpg.InterfaceError) <class 'asyncpg.exceptions._base.InterfaceError'>: cannot perform operation: another operation is in progress
```

What could be the cause ? i've tested a lot of different configurations and still have this issue.
My db is hosted on AWS RDS.
It's often leading to other issues afterwards like : 
(sqlalchemy.dialects.postgresql.asyncpg.InterfaceError) <class 'asyncpg.exceptions._base.InterfaceError'>: cannot use Connection.transaction() in a manually started transaction

Ideas on what I could test or a way to know if the operation is already in progress ?
Thanks

**Comment by grillazz** [comment]
@hhertogh already saw it on AWS RDS. As for some reason RDS is not closing db sessions like i.e. local postgres on docker.

So I suggest to simplify below
```
async def get_db(request: Request) -> AsyncGenerator[AsyncSession, None]:
    async with async_session() as session:
        yield session
```
and next consider explicitly commit() your queries in custom selectors etc.

If you would like to have session on request maybe you can consider do this on middleware i.e.
```
@app.middleware("http")
async def db_session_middleware(request: Request, call_next):
    response = Response("Internal server error", status_code=500)
    try:
        request.state.db_session = session()
        request.state.db_engine = engine
        response = await call_next(request)
    finally:
        request.state.db_session.close()
    return response
```

**Comment by grillazz** [comment]
@hhertogh also instead context manager you can have below meth:
```python
async def get_db() -> AsyncGenerator:
    try:
        session: AsyncSession = async_session_factory()
        logger.info(f"ASYNC Pool: {engine.pool.status()}")
        yield session
    except:
        await session.rollback()
        raise
    else:
        await session.commit()
    finally:
        await session.close()
```
and in logs you hsoudl get record like below
```
fastapi-sqlalchemy-asyncpg-app-1  | [11/04/22 18:51:31] INFO     [ MainThread:get_db:39 ] - ASYNC Pool: Pool size: 20  Connections in pool: 1 Current Overflow: -19 Current Checked out connections: 0                        database.py:39
```

**Comment by hhertogh** [comment]
Hey @grillazz ,
I've tested the two possibilities.
The simplified version does the number of connections going up so that at the end I've this kind of error:
_FATAL:  remaining connection slots are reserved for non-replication superuser connections_

The second option (new version of get_db) does not really make changes.

I've calls that might last between 5-15 seconds , this is maybe as well the reason ?

See here an example of a locust test:

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/9304294/200077075-6615292e-2e87-4d7e-8c77-66e8fc4ace55.png">

Thanks for your help

**Comment by grillazz** [comment]
Hi @hhertogh could you at same time run `SELECT * FROM pg_stat_activity` on your postgresql database and check if asyncpg is closing sessions ? If not try to add explicit `await session.commit()` for all the queries with shot version of `get_db`
